runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  LINE_CHANNEL_ACCESS_TOKEN: 'SWnTYljZDexfuVVILbVFZtYwSmwvETNtQ8VPThNLmW9lNNvBnEEoDDM39vLGx1eltiVqCumYtQyZvDE7HZd3X30Zob1Ec2puBXL+iPdq5mdbtfxKGq2GIMoqe5XIGRKeXi3uQ9YAHzp2BH5pdw+ACQdB04t89/1O/w1cDnyilFU='
  LINE_CHANNEL_SECRET: '9b2a0edc84246b578d1c1e9c37fe5896'

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /static
  static_dir: static
